### ISSUE TITLE
Class 'DOMPDFModule\View\Model\PdfModel' not found 

### ISSUE THREAD

**Issue by bhuvaneshwaran** [raykolbe/DOMPDFModule#16]
in my controller
use DOMPDFModule\View\Model\PdfModel;

  public function monthlyReportPdfAction()
    {
        $model = new PdfModel();
        $model->setOption('paperSize', 'a4');
        $model->setOption('paperOrientation', 'landscape');

```
    return $model;
}
```

clear my issue,
I just download ur  DOMPDFModule and put in my vendor

**Comment by raykolbe** [comment]
Hi @bhuvaneshwaran and @mamont77,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by raykolbe** [comment]
@bhuvaneshwaran and @mamont77 please try installing v0.4.0 via composer. If you continue to experience issues please open a new issue.

Closing issue due to age and proposed solution.
