### ISSUE TITLE
Problems on installation

### ISSUE THREAD

**Issue by vinigarcia87** [raykolbe/DOMPDFModule#18]
My composer.json:

```
"require": {
    "php": ">=5.3.3",
    "zendframework/zendframework": "2.2.*",

    "dino/dompdf-module": "dev-master"
}
```

Command executed:
$ php composer.phar update

```
Problem 1
   - Installation request for dino/dompdf-module dev-master -> satisfiable by dino/dompdf-module[dev-master].
   - dino/dompdf-module dev-master requires dompdf/dompdf dev-master#1abb9117a50c2854761bacaaff4b8a08257a1e8e -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

Take this opportunity to ask that the installation of the module dino/dompdf not depend on git. I don't use git on my environment, and only composer should be enough.

Thanks!
Waiting your answer to keep using this excellent module! :)

**Comment by vinigarcia87** [comment]
Hey, once again I'm trying to update project and it's not working. :(
Any of the fixes listed here works...
Can you please fix this? Your module is great! but it's kinda hard that I can update it easily. :S
Thanks!

**Comment by vinigarcia87** [comment]
I now getting this error:

 [RuntimeException]
 Failed to execute git status --porcelain --untracked-files=no
 'git' n?o ? reconhecido como um comando interno
 ou externo, um programa operável ou um arquivo em lotes.

**Comment by raykolbe** [comment]
Hi @vinigarcia87,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by raykolbe** [comment]
@FabianKoestring v0.4.0 resolves what you have observed.

@vinigarcia87 I do not know what your error message is about. This does not seem to be a DOMPDFModule specific error message. Please try updating your composer.json file to use v0.4.0. If you are still having trouble please open a new issue with detailed error information 👍 

Closing issue due to age and proposed solution(s).
