### ISSUE TITLE
setting filename does not trigger download

### ISSUE THREAD

**Issue by raymondelferink** [raykolbe/DOMPDFModule#19]
Hi Raymond,

Almost everything works smoothly for me, except:
You say somewhere that setting the filename will trigger download. I have set:
$model->setOption('fileName', 'voucher');

which should get me a download to voucher.pdf, but instead the pdf is opened in the browser window and when I save it from the acrobat plugin it has the name document.pdf

Am I doing something wrong, or have I stumbled upon something unexpected?

Thanks in advance, Raymond:-)

**Comment by raykolbe** [comment]
Hi @raymondelferink and @traedamatic,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by raykolbe** [comment]
Hi @raymondelferink 

I recently patched this in https://github.com/raykolbe/DOMPDFModule/pull/65. This will make it into the next release (0.5.0).
