### ISSUE TITLE
cant install via composer

### ISSUE THREAD

**Issue by nclundsten** [raykolbe/DOMPDFModule#22]
dev:master
and
v0.3.1

both have deps for different commits on dev master that cannot be satisfied,
checking out the "hotfix 18" branch doesnt make much sense either, as after new changes are made, they wont be sitting in that branch.

**Comment by raykolbe** [comment]
Hi @nclundsten,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by raykolbe** [comment]
@nclundsten v0.4.0 should resolve your issue. Please give this new release a go. If you are still having problems please open a new issue.

Closing issue due to age and resolution.
