### ISSUE TITLE
Manual setup guide

### ISSUE THREAD

**Issue by royyong** [raykolbe/DOMPDFModule#25]
Hi Ray,

I do not use Composer at the moment and I had tried to download your DOMPDFModule as well as the dompdf package from the DOMPDF site. Could you describe what else needs to be done besides the following in order to get it working?:
1) Putting them into the vendor directory:
vendor/dino/DOMPDFModule
vendor/dompdf/dompdf

2) Adding entry into the init_autoloader.php file:
Zend\Loader\AutoloaderFactory::factory(array(
            'Zend\Loader\StandardAutoloader' => array(
                'autoregister_zf' => true,
                'namespace' => array(
                    'dompdf'        => 'vendor/dompdf/dompdf',
                    'DOMPDFModule'  => 'vendor/dino/DOMPDFModule',
                )
            )
        ));

3) Adding entry into the autoload_classmap.php file:

return array(
    'dompdf'        => **DIR** . '/../../vendor/dompdf/dompdf/',
    'DOMPDFModule'  =>**DIR**.'/../../vendor/dino/DOMPDFModule/',//=>**DIR**.'/../../vendor/DOMPDFModule-master/',
);

I tried render and putting a PDF file in a directory but received the warning that the PdfModel module could not be found:
Class 'DOMPDFModule\View\Model\PdfModel' not found.

**Comment by raykolbe** [comment]
Hi @royyong,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by raykolbe** [comment]
Closing issue: This is not a supported method of installation.
