### ISSUE TITLE
0.3.1 Has dependency problem

### ISSUE THREAD

**Issue by Ponsjuh** [raykolbe/DOMPDFModule#26]
This is fixed by @BrunoSpy but isn't released yet. Can we have a anothe tag? or is something else still broken?

**Comment by raykolbe** [comment]
Hi @Ponsjuh,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by raykolbe** [comment]
@Ponsjuh v0.4.0 is now available. It is a tagged release of ebb367.

Closing issue due to age and resolution.
