### ISSUE TITLE
DOMPdf wouldn't work on my Linux box

### ISSUE THREAD

**Issue by stojko75** [raykolbe/DOMPDFModule#30]
Hi Reymond,

DOMPDF works fine on my Windows machine (WAMP). Everything's ok. 

However, after moving my code to Linux server (debian, nginx, php5-fpm) theres no error but page is not rendered as PDF. I see all elements, without error, but as HTML page, also CSS is not processed. Everything same on WAMP working fine. I have cheked and GD, DOM, MBString extensions everything is enabled. 

I dont know how to debug since there's no error. Please take a look at 
http://www.carskiducan.com/korpa/prikaziPDF/c710daf3d2e69f9e33b57c204f49ac5bdc035855  it should be rendered as pdf but it isn't. Any help appreciated.

Regards

**Comment by adriancallaghan** [comment]
There is no record with this id , id :

Proizvodi\Model\PorudzbinaTable->getSha1('c710daf3d2e69f9...')

**Comment by raykolbe** [comment]
Hi @stojko75 and @adriancallaghan,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by adriancallaghan** [comment]
Hi Raymond,

I would be happy to contribute to the project if it helps.

Thanks for the update

Adrian

**Comment by raykolbe** [comment]
@stojko75 I am not familiar with your code and setup. It appears that there is an issue as @adriancallaghan pointed out with `Proizvodi\Model\PorudzbinaTable->getSha1('c710daf3d2e69f9...')`. This is not code related to DOMPDFModule.

@adriancallaghan Any help would be appreciated.

Closing issue as this does not appear to be a DOMPDFModule issue. @stojko75 if you have more information pointing to DOMPDFModule as being the issue please create a new issue.
