### ISSUE TITLE
Need a new tag

### ISSUE THREAD

**Issue by tennaito** [raykolbe/DOMPDFModule#34]
Please could you generate a new tag? That´s because all the versions point to the dompdf/dompdf, dev-master. And The new dompdf/dompdf don´t has anymore the include folder. So when you "compose update" the project it gets an error in your /DOMPDFModule/Service/DOMPDFFactory.php Line 111. If you fix the dompdf/dompdf to the version 0.6.2 this error you be resolved.

**Comment by marcelotmelo** [comment]
+1

**Comment by raykolbe** [comment]
Hi @tennaito and @marcelotmelo,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by raykolbe** [comment]
@tennaito  and @marcelotmelo I have created v0.4.0 tag based on ebb367 commit.

Please try this new release. If you have problems please open a new issue so we can resolve it promptly.
