### ISSUE TITLE
Call to undefined method Zend\Mvc\View\Http\ViewManager::getResolver() 

### ISSUE THREAD

**Issue by marciodojr** [raykolbe/DOMPDFModule#37]
```
Fatal error: Call to undefined method Zend\Mvc\View\Http\ViewManager::getResolver() in /home/marcio/vhosts/vendor/dino/dompdf-module/src/DOMPDFModule/Mvc/Service/ViewPdfRendererFactory.php on line 39
```

@raykolbe since version 2.7.0 of [zend-mvc](https://github.com/zendframework/zend-mvc/blob/master/CHANGELOG.md#added-4) component, the [ViewManager](https://github.com/zendframework/zend-mvc/blob/master/src/View/Http/ViewManager.php) no longer has the methods `getResolver()` and `getRenderer()`. The `ViewResolver` and `ViewRenderer` now must be instanciated by factories. I sent a pull request #36 to solve this. I hope that helps.

**Comment by jgolebiewski** [comment]
+1

**Comment by charlienux** [comment]
+1

**Comment by effer89** [comment]
+1

**Comment by BrunoSpy** [comment]
+1

**Comment by unrl** [comment]
+1
Quick Fix: move back to zendframework/zendframework 2.5.2 instead of using 2.5.3

**Comment by Estigy** [comment]
+1
Anyone know when this will officially be resolved?

**Comment by andreasKrauseWebular** [comment]
+1
just solved one issue in zfc_user and updated the "zendframework/zend-mvc"

went back to "zendframework/zend-mvc": "<2.7"

**Comment by equinoxmatt** [comment]
This is a right pain.  Zend MVC has been completely refactored in zf 2.5.3.  I don't understand it well enough to fix it.  

As above, either revert back top ZF2 2.5.2 or change lock file to use zend-mvc <2.7

**Comment by andreasKrauseWebular** [comment]
Is there really no one caring any more? I also need the patch and we will all for sure! So I will also switch to netiul/DOMPDFModule!?

**Comment by bitkorn** [comment]
+1

**Comment by raykolbe** [comment]
Hi all,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by raykolbe** [comment]
This issue was fixed in https://github.com/raykolbe/DOMPDFModule/pull/60 and now exists in master.
