### ISSUE TITLE
PHP7 compatibility (update composer to dompdf 0.7.0)?

### ISSUE THREAD

**Issue by Ace-COM** [raykolbe/DOMPDFModule#39]
Hello,

I was testing the PHP7 compatibility, but it fails in current version of dompdf used. The creators of the dompdf have claimed it was fixed in the version 0.7.0 but I am not able to force the composer to use that file.

Is there more to be done to achieve PHP7 compatible code?

**Comment by raykolbe** [comment]
Hi @Ace-COM,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by raykolbe** [comment]
@Ace-COM The current Travis CI builds being performed for dev-master are passing w/PHP7. Is there a specific error message/stack trace you are receiving? What version of DOMPDFModule are you using?

**Comment by Ace-COM** [comment]
I did not try before I was sure the rest of my application runs php7 smoothly. Now I updated your module and it seems to run fine and it seems to be even faster than before. I just do not know what version of dompdf was installed (0.8.0 is out already).

Thank you.
