### ISSUE TITLE
Does this work with ZF3?

### ISSUE THREAD

**Issue by ghost** [raykolbe/DOMPDFModule#40]
Hello,
Will this work for ZF3? I received a exception for zf3.
For ZF2 its an awesome module to use.
Can you please inform me if it has been tested for zf3 before?

Thanks in advance

**Comment by raykolbe** [comment]
Hi @nepalkillerperson,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.

**Comment by juizmill** [comment]
I made a migration version for ZF3 if you can view and test https://github.com/raykolbe/DOMPDFModule/pull/57

**Comment by raykolbe** [comment]
Duplicate request. See #56.
