### ISSUE TITLE
zend-console dependency breaks existing code

### ISSUE THREAD

**Issue by graemedewe** [raykolbe/DOMPDFModule#51]
Hi, we have this dependency as a legacy piece of code, (with a require on dev-master) but today when I performed a composer update the dependency tree broke as you require zend-console 2.5.0 when we already have installed and is required by other vendors for zend-console 2.6.0. Is there a hard dependency on 2.5.0 or can this be set to 2.6.0?

**Comment by graemedewe** [comment]
could you create a tag of this https://github.com/raykolbe/DOMPDFModule/commit/ebb3678 as this is the last working version we have

**Comment by grantblue** [comment]
Having the same issue.

**Comment by DiloWagner** [comment]
I have the same issue!

**Comment by raykolbe** [comment]
Hi all,

I apologize for the issue. As is long overdue I have cut a v0.4.0 release based on ebb3678.

Please update your composer.json files to use this release.

Thank you and again I apologize for any inconvenience this has caused.

I will leave this issue open for a little bit to make it easier for others to discover/comment on.

**Comment by raykolbe** [comment]
@graemedewe, et. al. I'll work on getting dev-master to the correct/stable versions soon. Seems like 2.6 is most recent in 2.x branch.

Once I've fixed this in dev-master could I ask a big favor and have one of you try to install it as a dependency of your project?

**Comment by DiloWagner** [comment]
Thanks @raykolbe... **v0.4.0** it's work!

**Comment by raykolbe** [comment]
👍 @DiloWagner

**Comment by raykolbe** [comment]
@graemedewe et. al. I just noticed the typo in the composer.json file https://github.com/raykolbe/DOMPDFModule/blob/master/composer.json#L26

This is being corrected in https://github.com/raykolbe/DOMPDFModule/pull/53.
