### ISSUE TITLE
Create a tag @ #a2e2e15

### ISSUE THREAD

**Issue by digitalsounds** [raykolbe/DOMPDFModule#71]
Can you please create a tag at this commit #a2e2e154ffc84c724ba6a2c1ae63a948d8fc0e1d

As this was the last version before the minimum dompdf version constraint was increased from ^0.6.0 to ^0.8.0 in your composer.json as my code is not compatible with the newer version of dompdf, so i can not use dev-master.

**Comment by raykolbe** [comment]
Hi @digitalsounds.

For production code I would suggest using a released version of DompdfModule. The current release is 0.4.0. You can update your composer.json file by running the following:

```
composer require dino/dompdf-module:"^0.4.0"
```

Alternatively you can you require the specific commit you desire in your composer.json file.

```
composer require dino/dompdf-module:"dev-master#a2e2e154ffc84c724ba6a2c1ae63a948d8fc0e1d"
```

Given both Dompdf and DompdfModule are zero based releases you can expect that the minimum required version will continue to be incremented each release. The 0.5.0 release _will_ include the requirement for Dompdf 0.8.0+.
