### ISSUE TITLE
Saving the PDF

### ISSUE THREAD

**Issue by manuakasam** [raykolbe/DOMPDFModule#9]
Hey Ray,

is there a way to save the generated PDF-File?
I am talking about saving it on server-side to not re-render already generated PDF Files that have not been changed (or for versioning control as an example).

I assume i have to attach a listener to the `renderer.post` event. Have you ever done this? I assume this would be a highly requested feature for people working with the Module.

IF you have done this it would be awesome if you could provide the code for such a thing. I'll be trying to figure it out for myself though ;-)

**Comment by raykolbe** [comment]
Hi all,

As you've noticed DOMPDFModule hasn't received the time and attention it deserves. I understand how frustrating this is and I'm sorry you've had to deal with this frustration 😢 

I'm currently taking steps to stabilize DOMPDFModule which includes code updates as well as creating a backlog that will ensure its continued success.

You can follow project [Phoneix ](https://github.com/raykolbe/DOMPDFModule/projects/1) to see what immediate work is being prioritized.

Thank you for your understanding and patience.
